# Generated by Django 4.1.1 on 2022-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Babes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
            ],
        ),
    ]
