# Generated by Django 4.1.1 on 2022-11-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='babes',
            table='Babies',
        ),
    ]
