# Generated by Django 4.1.1 on 2022-10-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('video_title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('video_file_type', models.CharField(max_length=250)),
            ],
        ),
    ]
